export const PATHS = {
  HOME: "/",
  LOGIN: "/account/login",
};

export const NAVIGATIONS = [
  {
    title: "新着商品",
    listItems: [
      { title: "新着商品一覧", href: "/collections/" },
      { title: "10月3日発売商品", href: "/collections/" },
      { title: "9月30日予約商品", href: "/collections/" },
      { title: "9月26日発売商品", href: "/collections/" },
      { title: "9月19日発売商品", href: "/collections/" },
      { title: "9月12日発売商品", href: "/collections/" },
      { title: "9月5日発売商品", href: "/collections/" },
      { title: "8月29日発売商品", href: "/collections/" },
      { title: "8月22日発売商品", href: "/collections/" },
      { title: "8月8日予約商品", href: "/collections/" },
    ],
  },
  {
    title: "再入荷商品",
    listItems: [
      {
        title: "再入荷商品一覧",
        href: "/collections/",
      },
      {
        title: "10月2日再入荷商品",
        href: "/collections/",
      },
      {
        title: "9月25日再入荷商品",
        href: "/collections/",
      },
      {
        title: "9月18日再入荷商品",
        href: "/collections/",
      },
    ],
  },
  {
    title: "キャラクターから探す",
    listItems: [
      { title: "ちいかわ", href: "/collections/" },
      { title: "ハチワレ", href: "/collections/" },
      { title: "うさぎ", href: "/collections/" },
      { title: "モモンガ", href: "/collections/" },
      { title: "くりまんじゅう", href: "/collections/" },
      { title: "ラッコ", href: "/collections/" },
      { title: "シーサー", href: "/collections/" },
      { title: "古本屋", href: "/collections/" },
      { title: "あのこ", href: "/collections/" },
      { title: "でかつよ", href: "/collections/" },
      { title: "オデ", href: "/collections/" },
      { title: "キメラ", href: "/collections/" },
      { title: "鎧さん", href: "/collections/" },
      { title: "カブトムシ", href: "/collections/" },
      { title: "ゴブリン", href: "/collections/" },
      { title: "星", href: "/collections/" },
      { title: "キャラクター一覧", href: "/collections/" },
    ],
  },
  {
    title: "シリーズから探す",
    listItems: [
      { title: "Chiikawa Baby", href: "/collections/" },
      { title: "ちいかわ てんし♡あくま", href: "/collections/" },
      { title: "ちいかわ×MLB TOKYO SERIES", href: "/collections/" },
      { title: "ちいかわ パラレルワールド！？", href: "/collections/" },
      { title: "ちいかわベーカリー", href: "/collections/" },
      { title: "ちいかわ寿司", href: "/collections/" },
      {
        title: "ちいかわ シーサー祭り！！！＆シーサーのおみやげやさん",
        href: "/collections/",
      },
      { title: "ちいかわ×読売ジャイアンツ", href: "/collections/" },
      { title: "ちいかわラーメン豚", href: "/collections/" },
      { title: "まじかるちいかわ＆超まじかるちいかわ", href: "/collections/" },
      { title: "ちいかわレストラン", href: "/collections/" },
      { title: "ちいかわ×阪急電車", href: "/collections/" },
      { title: "ちいかわ×ホークス", href: "/collections/" },
      { title: "ちいかわ お出かけ楽しみ！", href: "/collections/" },
      { title: "ちいかわ水族館", href: "/collections/" },
      { title: "ちいかわ×サンリオキャラクターズ", href: "/collections/" },
      { title: "ちいかわ 東京みやげ", href: "/collections/" },
      { title: "ちいかわ ワクワクゆうえんち", href: "/collections/" },
      { title: "ちいかわ飯店", href: "/collections/" },
      { title: "ちいかわらんど", href: "/collections/" },
      { title: "シリーズ一覧", href: "/collections/" },
    ],
  },
  {
    title: "商品カテゴリから探す",
    listItems: [
      { title: "ぬいぐるみ・マスコット", href: "/collections/" },
      { title: "雑貨", href: "/collections/" },
      { title: "バックパック", href: "/collections/" },
      { title: "インテリア", href: "/collections/" },
      { title: "アパレル", href: "/collections/" },
      { title: "文房具", href: "/collections/" },
      { title: "タオル", href: "/collections/" },
      { title: "キッチン", href: "/collections/" },
      { title: "PC・スマホグッズ", href: "/collections/" },
      { title: "アメニティ", href: "/collections/" },
      { title: "アウトドア", href: "/collections/" },
      { title: "おもちゃ・パズル", href: "/collections/" },
      { title: "食品", href: "/collections/" },
      { title: "予約商品", href: "/collections/" },
      { title: "全商品", href: "/collections/" },
      { title: "カテゴリー一覧", href: "/collections/" },
    ],
  },
  {
    title: "ご利用ガイド",
    href: "/pages/guide",
  },
];
